# Generated by Django 5.2 on 2025-08-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('peticion_grupo', models.TextField(blank=True, help_text='Descripción detallada de la petición de catering del grupo musical', verbose_name='Petición del Grupo')),
                ('tipo_evento', models.CharField(blank=True, help_text='Tipo de evento para el cual se solicita el catering', max_length=100, verbose_name='Tipo de Evento')),
                ('numero_personas', models.PositiveIntegerField(blank=True, help_text='Número estimado de personas para el catering', null=True, verbose_name='Número de Personas')),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto estimado para el catering', max_digits=10, null=True, verbose_name='Presupuesto Estimado')),
                ('fecha_evento', models.DateTimeField(blank=True, help_text='Fecha y hora del evento', null=True, verbose_name='Fecha del Evento')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación donde se realizará el evento', max_length=200, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor de catering seleccionado', max_length=200, verbose_name='Proveedor')),
                ('contacto_proveedor', models.CharField(blank=True, help_text='Información de contacto del proveedor', max_length=200, verbose_name='Contacto del Proveedor')),
                ('notas_adicionales', models.TextField(blank=True, help_text='Notas adicionales sobre el catering', verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Catering',
                'verbose_name_plural': 'Catering',
                'ordering': ['-fecha_evento', '-created_at'],
                'indexes': [models.Index(fields=['estado', 'fecha_evento'], name='CATERING_ca_estado_4b66ab_idx'), models.Index(fields=['proveedor'], name='CATERING_ca_proveed_4bb763_idx')],
            },
        ),
    ]
