# Generated by Django 5.0.6 on 2025-09-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REPERTORIE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('nombre', models.CharField(help_text='Nombre del género', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='repertorio',
            new_name='REPERTORIE__genero__b7aaf4_idx',
            old_name='REPERTORIE__genero_27a1cc_idx',
        ),
        migrations.AddField(
            model_name='repertorio',
            name='letra',
            field=models.TextField(blank=True, help_text='Letra de la canción', null=True, verbose_name='Letra'),
        ),
        migrations.AddField(
            model_name='repertorio',
            name='pista_audio',
            field=models.FileField(blank=True, help_text='Pista de audio de la canción', null=True, upload_to='pistas_audio/', verbose_name='Pista de audio'),
        ),
        migrations.AddField(
            model_name='repertorio',
            name='progresion_acordes',
            field=models.TextField(blank=True, help_text='Acordes utilizados en la canción', null=True, verbose_name='Acordes'),
        ),
        migrations.AlterField(
            model_name='repertorio',
            name='genero',
            field=models.ForeignKey(help_text='Género musical de la canción', null=True, on_delete=django.db.models.deletion.SET_NULL, to='REPERTORIE.generos', verbose_name='Género'),
        ),
    ]
