# Generated by Django 5.2 on 2025-08-27 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del equipo de audio', max_length=200, verbose_name='Nombre del Equipo')),
                ('tipo', models.CharField(choices=[('altavoces', 'Altavoces'), ('microfonos', 'Micrófonos'), ('mezcladores', 'Mezcladores'), ('amplificadores', 'Amplificadores'), ('instrumentos', 'Instrumentos'), ('iluminacion', 'Iluminación'), ('cables', 'Cables'), ('soportes', 'Soportes'), ('otros', 'Otros')], db_index=True, default='altavoces', max_length=50, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(blank=True, help_text='Marca del equipo', max_length=200, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, help_text='Modelo específico del equipo', max_length=200, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie único del equipo', max_length=200, null=True, unique=True, verbose_name='Número de Serie')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento'), ('averiado', 'Averiado'), ('vendido', 'Vendido')], db_index=True, default='disponible', max_length=50, verbose_name='Estado')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra del equipo', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra')),
                ('fecha_compra', models.DateField(blank=True, help_text='Fecha en que se adquirió el equipo', null=True, verbose_name='Fecha de Compra')),
                ('garantia_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual está vigente la garantía', null=True, verbose_name='Garantía Hasta')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del equipo', max_length=200, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el equipo', verbose_name='Observaciones')),
                ('cantidad_equipo', models.PositiveIntegerField(blank=True, help_text='Cantidad de equipos', null=True, verbose_name='Cantidad de Equipos')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del equipo', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del equipo de audio', null=True, upload_to='equipos_audio/', verbose_name='Imagen del equipo')),
            ],
            options={
                'verbose_name': 'Equipo de Audio',
                'verbose_name_plural': 'Equipos de Audio',
                'ordering': ['nombre', 'marca', 'modelo'],
                'indexes': [models.Index(fields=['tipo', 'estado'], name='AUDIO_audio_tipo_d02231_idx'), models.Index(fields=['marca', 'modelo'], name='AUDIO_audio_marca_d0c954_idx')],
            },
        ),
    ]
