# Generated by Django 5.2 on 2025-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUDIO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioequipment',
            name='numero_bocinas',
        ),
        migrations.AddField(
            model_name='audioequipment',
            name='cantidad_equipo',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de equipos)', null=True, verbose_name='Cantidad de Equipos'),
        ),
    ]
