# Generated by Django 5.2 on 2025-08-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='MEXICO.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('asentamiento', models.CharField(blank=True, max_length=25, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colonias', to='MEXICO.municipio')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
                'db_table': 'colonias',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='MEXICO.pais'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['estado'], name='index_estado'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['municipio'], name='index_municipio'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['nombre'], name='index_nombre'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['asentamiento'], name='index_asentamiento'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['codigo_postal'], name='index_codigo_postal'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['ciudad'], name='index_ciudad'),
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['pais'], name='index_pais'),
        ),
    ]
