# Generated by Django 5.2 on 2025-08-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos del cliente', max_length=255, verbose_name='Apellidos')),
                ('telefono', models.CharField(help_text='Número de teléfono del cliente', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, help_text='Dirección completa del cliente', max_length=500, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad del cliente', max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal del cliente', max_length=10, verbose_name='Código Postal')),
                ('tipo_cliente', models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa'), ('organizacion', 'Organización')], default='particular', help_text='Tipo de cliente: particular, empresa u organización', max_length=20, verbose_name='Tipo de Cliente')),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa u organización (si aplica)', max_length=255, verbose_name='Empresa/Organización')),
                ('nif_cif', models.CharField(blank=True, help_text='Número de identificación fiscal (si aplica)', max_length=20, verbose_name='NIF/CIF')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', verbose_name='Observaciones')),
                ('frecuencia', models.CharField(choices=[('frecuente', 'Frecuente'), ('regular', 'Regular'), ('ocasional', 'Ocasional')], default='ocasional', help_text='Frecuencia de contratación del cliente', max_length=20, verbose_name='Frecuencia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='ClienteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('tipo_red_social', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('other', 'Otro')], help_text='Tipo de red social', max_length=20, verbose_name='Tipo de red social')),
                ('enlace', models.URLField(help_text='Enlace a la red social', verbose_name='Enlace')),
                ('nombre_usuario', models.CharField(blank=True, help_text='Nombre de usuario en la red social (opcional)', max_length=100, verbose_name='Nombre de usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='CLIENTS.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Red Social del Cliente',
                'verbose_name_plural': 'Redes Sociales del Cliente',
                'ordering': ['cliente', 'tipo_red_social'],
                'unique_together': {('cliente', 'tipo_red_social', 'enlace')},
            },
        ),
    ]
