# Generated by Django 5.2 on 2025-08-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='client',
            name='direccion',
        ),
        migrations.AddField(
            model_name='client',
            name='colonia',
            field=models.CharField(blank=True, help_text='Colonia o asentamiento del cliente', max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='client',
            name='direccion_completa',
            field=models.CharField(blank=True, help_text='Calle, número y referencias adicionales', max_length=500, verbose_name='Dirección Completa'),
        ),
        migrations.AddField(
            model_name='client',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado del cliente', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='client',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio del cliente', max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='client',
            name='pais',
            field=models.CharField(default='México', help_text='País del cliente', max_length=50, verbose_name='País'),
        ),
    ]
