# Generated by Django 5.2 on 2025-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='redes_sociales_link',
            field=models.URLField(blank=True, help_text='Enlace a la red social seleccionada', verbose_name='Enlace a red social'),
        ),
        migrations.AlterField(
            model_name='client',
            name='redes_sociales',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('other', 'Otro')], default='other', help_text='Enlaces a redes sociales del cliente', max_length=20, verbose_name='Redes sociales'),
        ),
    ]
