# Generated by Django 5.2 on 2025-08-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTS', '0002_client_redes_sociales_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='redes_sociales',
        ),
        migrations.RemoveField(
            model_name='client',
            name='redes_sociales_link',
        ),
        migrations.CreateModel(
            name='ClienteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('tipo_red_social', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('reddit', 'Reddit'), ('other', 'Otro')], help_text='Tipo de red social', max_length=20, verbose_name='Tipo de red social')),
                ('enlace', models.URLField(help_text='Enlace a la red social', verbose_name='Enlace')),
                ('nombre_usuario', models.CharField(blank=True, help_text='Nombre de usuario en la red social (opcional)', max_length=100, verbose_name='Nombre de usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='CLIENTS.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Red Social del Cliente',
                'verbose_name_plural': 'Redes Sociales del Cliente',
                'ordering': ['cliente', 'tipo_red_social'],
                'unique_together': {('cliente', 'tipo_red_social', 'enlace')},
            },
        ),
    ]
