# Generated by Django 5.2 on 2025-08-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTS', '0002_remove_client_ciudad_remove_client_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='direccion_completa',
        ),
    ]
