# Generated by Django 5.2 on 2025-08-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTS', '0003_remove_client_redes_sociales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesocialmedia',
            name='nombre_usuario',
        ),
    ]
