# Generated by Django 5.2 on 2025-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTS', '0004_remove_clientesocialmedia_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesocialmedia',
            name='nombre_usuario',
            field=models.CharField(blank=True, help_text='Nombre de usuario en la red social (opcional)', max_length=100, verbose_name='Nombre de usuario'),
        ),
    ]
