# Generated by Django 5.2.2 on 2025-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIGS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='frecuencia',
            field=models.CharField(choices=[('frecuente', 'Frecuente'), ('regular', 'Regular'), ('ocasional', 'Ocasional')], default='ocasional', help_text='Frecuencia de contratación del cliente', max_length=20, verbose_name='Frecuencia'),
        ),
    ]
