# Generated by Django 5.2.2 on 2025-06-20 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIGS', '0002_alter_cliente_frecuencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo_audio',
            options={'ordering': ['nombre', 'marca', 'modelo'], 'verbose_name': 'Equipo de audio', 'verbose_name_plural': 'Equipos de audio'},
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento'), ('averiado', 'Averiado'), ('vendido', 'Vendido')], default='disponible', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='garantia_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Garantía Hasta'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='nombre',
            field=models.CharField(default='Equipo sin nombre', max_length=200, verbose_name='Nombre del Equipo'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='tipo',
            field=models.CharField(choices=[('altavoces', 'Altavoces'), ('microfonos', 'Micrófonos'), ('mezcladores', 'Mezcladores'), ('amplificadores', 'Amplificadores'), ('instrumentos', 'Instrumentos'), ('iluminacion', 'Iluminación'), ('cables', 'Cables'), ('soportes', 'Soportes'), ('otros', 'Otros')], default='altavoces', max_length=50, verbose_name='Tipo de Equipo'),
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='equipo_audio',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='equipo_audio',
            name='marca',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo_audio',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo_audio',
            name='numero_bocinas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de bocinas'),
        ),
        migrations.AlterField(
            model_name='equipo_audio',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
