# Generated by Django 5.2 on 2025-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIGS', '0003_alter_equipo_audio_options_equipo_audio_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo_audio',
            name='precio',
        ),
        migrations.AddField(
            model_name='equipo_audio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos_audio/', verbose_name='Imagen del equipo'),
        ),
    ]
