# Generated by Django 5.2 on 2025-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='image_profile',
            field=models.ImageField(blank=True, help_text='Imagen de perfil', null=True, upload_to='profile_pictures/', verbose_name='Imagen de perfil'),
        ),
    ]
