# Generated by Django 5.2 on 2025-08-25 06:32

import AUTH.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0002_alter_usercustom_image_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercustom',
            managers=[
                ('objects', AUTH.models.UserCustomManager()),
            ],
        ),
    ]
