# Generated by Django 5.2 on 2025-08-27 19:54

import GIGS.EVENT_PHOTOS.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CLIENTS', '0001_initial'),
        ('CONTRACT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indica si el registro se encuentra activo', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Fecha y hora de la ultima actualización del registro', verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora de borrado del registro', null=True, verbose_name='Fecha de borrado')),
                ('nombre_foto', models.CharField(help_text='Nombre descriptivo de la foto', max_length=255)),
                ('foto', models.ImageField(help_text='Archivo de imagen (JPG, PNG, WEBP)', upload_to=GIGS.EVENT_PHOTOS.models.event_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('fecha_foto', models.DateField(help_text='Fecha en que se tomó la foto')),
                ('evento', models.CharField(help_text='Nombre del evento', max_length=255)),
                ('fecha_evento', models.DateField(help_text='Fecha del evento')),
                ('tipo_evento', models.CharField(choices=[('birthday', 'Cumpleaños'), ('wedding', 'Boda'), ('quinceañera', 'Quinceañera'), ('baptism', 'Bautizo'), ('communion', 'Primera Comunión'), ('graduation', 'Graduación'), ('anniversary', 'Aniversario'), ('corporate', 'Evento Corporativo'), ('baby_shower', 'Baby Shower'), ('bridal_shower', 'Despedida de Soltera'), ('christmas', 'Navidad'), ('new_year', 'Año Nuevo'), ('concert', 'Concierto'), ('otros', 'Otros')], default='otros', help_text='Tipo de evento', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación donde se tomó la foto', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la foto o momento capturado')),
                ('fotografo', models.CharField(blank=True, help_text='Nombre del fotógrafo', max_length=255)),
                ('publicas', models.BooleanField(default=True, help_text='Si la foto es visible en la galería pública')),
                ('destacadas', models.BooleanField(default=False, help_text='Si la foto aparece en la sección destacadas')),
                ('ancho_imagen', models.PositiveIntegerField(blank=True, help_text='Ancho de la imagen en píxeles', null=True)),
                ('alto_imagen', models.PositiveIntegerField(blank=True, help_text='Alto de la imagen en píxeles', null=True)),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asociado al evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_eventos', to='CLIENTS.client')),
                ('contrato', models.ForeignKey(blank=True, help_text='Contrato asociado al evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_evento', to='CONTRACT.contract')),
            ],
            options={
                'verbose_name': 'Foto de Evento',
                'verbose_name_plural': 'Fotos de Eventos',
                'db_table': 'event_photos',
                'ordering': ['-fecha_evento', '-fecha_foto', '-created_at'],
                'indexes': [models.Index(fields=['fecha_evento'], name='event_photo_fecha_e_202212_idx'), models.Index(fields=['fecha_foto'], name='event_photo_fecha_f_86fb5b_idx'), models.Index(fields=['evento'], name='event_photo_evento_fa23b2_idx'), models.Index(fields=['tipo_evento'], name='event_photo_tipo_ev_7f09ae_idx'), models.Index(fields=['publicas'], name='event_photo_publica_447191_idx'), models.Index(fields=['destacadas'], name='event_photo_destaca_fe7007_idx'), models.Index(fields=['cliente'], name='event_photo_cliente_2b7a71_idx'), models.Index(fields=['contrato'], name='event_photo_contrat_840907_idx'), models.Index(fields=['fotografo'], name='event_photo_fotogra_a9ae41_idx'), models.Index(fields=['created_at'], name='event_photo_created_4ceda0_idx')],
            },
        ),
    ]
